Fix triple-slash reference in complied output, breaking TS consumers
tracked-tools/ember-async-data pull request #704
Opened 2023-08-29 17:49 UTC by NullVoxPopuli

Related fixes:
- https://github.com/jmurphyau/ember-truth-helpers/pull/188/files/ce510514b8af75e1dda509162190cced07bf1aee..b21676dacb9585ae4bb63d5e2cf0e9f5cb607d0f#diff-8afe3e4876b5c49d5ffaf6c8f18ae139f02686841982ca9b8ed2020dec8a8cd8
- https://github.com/tildeio/ember-element-helper/pull/113

Any import from `@ember/component` (or its subpaths), where `@ember/component` types are exposed in the declarations, ends up inserting `/// <reference>` entries at the top of the file.

![image](https://github.com/tracked-tools/ember-async-data/assets/199018/e643cf16-5277-43d9-94a5-40b1117d7fa0)

This made upgrading to v1.0.2 of ember-async-data impossible for folks using any ember-source version that has a different set of types than the `ember-source` version that `ember-async-data` is developed with. (too new, no preview types, provided by stable. too old, no preview types, provided by `@types/*`).

2023-08-29 17:56 UTC, SergeAstapov commented
@NullVoxPopuli thank you for doing this here! Had the exact same thought.

@NullVoxPopuli one concern though about support:
readme currently says `Ember.js v3.28 or above (requires Octane Edition)` hence I assume we need to add `ember-functions-as-helper-polyfill` to avoid major release

2023-08-29 18:09 UTC, NullVoxPopuli commented
> hence I assume we need to add ember-functions-as-helper-polyfill to avoid major release

just added! thanks!

2023-08-29 22:57 UTC, chriskrycho commented on ember-async-data/src/helpers/load.ts
> +}
Note the comment immediately above this line. 😂 The change may be fine to do as a non-breaking change; however, this doesn't overall seem like the right move. I followed the saga of how you got here, but I believe all this *should* actually require is to explicitly use `import type { FunctionBasedHelper } from '@ember/component/helper';` and then to name the type explicitly, or perhaps even `import type { HelperLike } from '@glimmer/template'` (though I would not think we would need the latter). I *suspect* the `reference` type emit is a function of the fact that TS identifies it *needs* to name the type because of the use of `helper()` here and the lack of any other name for it.

2023-08-29 23:00 UTC, chriskrycho commented on ember-async-data/type-tests/load-test.ts
> +>();
`expect-type` has a type utility for this, though we already cover this above.

```suggestion
expectTypeOf(load("hello")).returns.toEqualTypeOf<TrackedAsyncData<string>>();
```

2023-08-29 23:02 UTC, chriskrycho requested changes
If you do as suggested here and explicitly name the type, I *believe* you can drop the other changes here, which would be preferable for now. Switching to the plain function as helper can come in a later PR that way, and avoid introducing any other changes for this one TS fix. Do let me know if that doesn't work, though!

2023-09-02 03:43 UTC, SergeAstapov commented
> If you do as suggested here and explicitly name the type, I believe you can drop the other changes here, which would be preferable for now. 

as per #705 it does not seem viable.

@chriskrycho updated this PR per the plan outlined in https://github.com/tracked-tools/ember-async-data/pull/705#discussion_r1310373011

please let us know if this looks good to proceed or if you have any concerns. Thank you for suggestions and ideas here and in the other PR!

2023-10-01 03:25 UTC, merged

2024-01-10 03:13 UTC, NullVoxPopuli commented
Made a tool to help out in the future: https://github.com/NullVoxPopuli/fix-bad-declaration-output

2024-01-10 18:15 UTC, chriskrycho commented
🎉